spring:
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    default-schema: public

  application:
    name: EduPlanner
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  docker:
    compose:
      lifecycle-management: start_only
      file: classpath:compose.yaml
  threads:
    virtual:
      enabled: true
  jackson:
    time-zone: America/Argentina/Buenos_Aires

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_TIME_EXPIRATION}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
app:
  mail:
    from: ${MAIL_FROM:changemeinprod@example.com}
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
  frontend-url: ${FRONTEND_URL:https://placeholder.remove.me}
  datasource:
    database-url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/eduplanner}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger
    operations-sorter: method
    tags-sorter: alpha

server:
  port: ${SERVER_PORT:8080}

cloudinary:
  cloud-name: ${CLOUD_NAME:dqc7crpkq}
  api-key: ${API_KEY:442165733268754}
  api-secret: ${API_SECRET:ZcelzzcvTGZdc0-dzFzXjIUBQVc}

