spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    default-schema: public

  application:
    name: EduPlanner
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  docker:
    compose:
      lifecycle-management: start_only
      file: classpath:compose.yaml
  threads:
    virtual:
      enabled: true
  jackson:
    time-zone: America/Argentina/Buenos_Aires

jwt:
  secret-key : ${JWT_SECRET_KEY}
  expiration : ${JWT_TIME_EXPIRATION}
  refresh-token :
    expiration : ${JWT_REFRESH_TOKEN_EXPIRATION}
app:
  datasource:
    database-url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
springdoc:
  api-docs:
    enabled: true
    path: /docs/api-docs
  swagger-ui:
    enabled: true
    path: /docs/swagger
    operations-sorter: method
    tags-sorter: alpha

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    liquibase: DEBUG
#    com.zaxxer.hikari: DEBUG