spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  application:
    name: EduPlanner
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true
jwt:
  secret-key : ${jwt.secret.key}
  expiration : ${jwt.time.expiration}
  refresh-token :
    expiration : ${jwt.refresh.token.expiration}