spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  application:
    name: EduPlanner
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true