spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eduplanner}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: America/Argentina/Buenos_Aires
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
  application:
    name: EduPlanner
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true
  jackson:
    time-zone: America/Argentina/Buenos_Aires

jwt:
  secret-key : ${JWT_SECRET_KEY}
  expiration : ${JWT_TIME_EXPIRATION}
  refresh-token :
    expiration : ${JWT_REFRESH_TOKEN_EXPIRATION}