-- liquibase formatted sql

-- changeset crist:1737069281696-1
CREATE TABLE course_class_days
(
    course_id  BIGINT NOT NULL,
    class_days VARCHAR(255)
);

-- changeset crist:1737069281696-2
CREATE TABLE courses
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             INTEGER                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by          VARCHAR(255)                            NOT NULL,
    last_modified_by    VARCHAR(255),
    name                VARCHAR(255),
    class_start_time    TIME WITHOUT TIME ZONE                  NOT NULL,
    blocks_before_lunch INTEGER                                 NOT NULL,
    blocks_after_lunch  INTEGER                                 NOT NULL,
    block_duration      BIGINT                                  NOT NULL,
    break_duration      BIGINT                                  NOT NULL,
    lunch_duration      BIGINT                                  NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

-- changeset crist:1737069281696-3
CREATE TABLE schedule_blocks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    order_number     INTEGER                                 NOT NULL,
    schedule_id      BIGINT                                  NOT NULL,
    subject_id       BIGINT,
    day_of_week      VARCHAR(255)                            NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    start_time       TIME WITHOUT TIME ZONE                  NOT NULL,
    end_time         TIME WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_schedule_blocks PRIMARY KEY (id)
);

-- changeset crist:1737069281696-4
CREATE TABLE schedules
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    course_id        BIGINT,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

-- changeset crist:1737069281696-5
CREATE TABLE subjects
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255)                            NOT NULL,
    last_modified_by VARCHAR(255),
    name             VARCHAR(255)                            NOT NULL,
    color            VARCHAR(255)                            NOT NULL,
    type             VARCHAR(255)                            NOT NULL,
    course_id        BIGINT,
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

-- changeset crist:1737069281696-6
ALTER TABLE schedules
    ADD CONSTRAINT uc_schedules_course UNIQUE (course_id);

-- changeset crist:1737069281696-7
ALTER TABLE subjects
    ADD CONSTRAINT uc_subjects_name UNIQUE (name);

-- changeset crist:1737069281696-8
ALTER TABLE schedules
    ADD CONSTRAINT FK_SCHEDULES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

-- changeset crist:1737069281696-9
ALTER TABLE schedule_blocks
    ADD CONSTRAINT FK_SCHEDULE_BLOCKS_ON_SCHEDULE FOREIGN KEY (schedule_id) REFERENCES schedules (id);

-- changeset crist:1737069281696-10
ALTER TABLE schedule_blocks
    ADD CONSTRAINT FK_SCHEDULE_BLOCKS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

-- changeset crist:1737069281696-11
ALTER TABLE subjects
    ADD CONSTRAINT FK_SUBJECTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

-- changeset crist:1737069281696-12
ALTER TABLE course_class_days
    ADD CONSTRAINT fk_course_class_days_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

